name: On-demand VM Build+Test

on: 
  workflow_dispatch:
  
env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
  ALLURE_PROJECT_ID: ${{ vars.ALLURE_PROJECT_ID }}
  
jobs:

  start-runner:
    name: Start self-hosted YC runner
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: start
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          folder-id: ${{secrets.YC_FOLDER}}
          image-id: fd8snjpoq85qqv0mk9gi
          disk-size: 930GB
          disk-type: network-ssd-nonreplicated
          cores: 32
          memory: 64GB
          core-fraction: 100
          zone-id: ru-central1-b
          subnet-id: ${{secrets.YC_SUBNET}}

  prepare-vm:
    needs: start-runner
    uses: ./.github/workflows/prepare_vm_for_build.yaml
    with:
      runner_label: ${{ needs.start-runner.outputs.label }}

  build-and-test:
    needs: 
    - start-runner
    - prepare-vm
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner

    steps:
    - name: Verify ccache
      shell: bash
      run: ccache -p
    - name: Checkout YDB
      uses: actions/checkout@v3
    - name: Configure YDB
      shell: bash
      run: |
        pwd
        mkdir ../build
        mkdir ../test_reports
        cd ../build
        rm -rf *
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_TOOLCHAIN_FILE=../ydb/clang.toolchain ../ydb
    - name: Build YDB
      shell: bash
      run: |
        cd ../build
        ninja
    - name: Test YDB
      shell: bash
      run: |
        cd ../build/ydb
        mkdir -p $(pwd)/../../test_reports
        # Sed to remove coloring
        GTEST_OUTPUT="xml:$(pwd)/../../test_reports/" Y_UNITTEST_OUTPUT="xml:$(pwd)/../../test_reports/" \
          ~/allurectl watch --results $(pwd)/../../test_reports/ -- \
          ctest -j28 --timeout 1200 --force-new-ctest-process --output-on-failure \
            --output-junit $(pwd)/../../test_reports/ctest_report.xml \
            -L '(SMALL|MEDIUM)' | \
          sed -e 's/\x1b\[[0-9;]*m//g' | \
          tee testrun.log | \
          grep -E '(Test\s*#.*\*\*\*|\[FAIL\])|.*tests passed,.*tests failed out of'
  
  stop-runner:
    name: Stop self-hosted YC runner
    needs:
      - start-runner # required to get output from the start-runner job
      - build-and-test # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Stop YC runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: stop
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          instance-id: ${{ needs.start-runner.outputs.instance-id }}
