name: Sync cmakebuild with main
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  REPO: ${{ github.repository }}
  TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=dtm::$(date +'%y%m%d-%H%M')"
    - name: Sync
      run: |
        currsha=$(curl -s -H "Accept: application/vnd.github.VERSION.sha" https://api.github.com/repos/$REPO/commits/rightlib)
        echo "Current rightlib sha: ${currsha}"
        lastsha=$(curl -s https://raw.githubusercontent.com/$REPO/main/ydb/ci/rightlib.txt)
        echo "Last imported rightlib sha: ${lastsha}"
        if [ "${currsha}" == "${lastsha}" ];then
          echo "No new commits on the rightlib branch to merge, exiting"
          exit 0
        fi
        # Fetch rightlib
        git clone -b rightlib --shallow-exclude main https://$TOKEN@github.com/$REPO.git ydb
        git config --global user.email "alex@ydb.tech"
        git config --global user.name "Alexander Smirnov"
        cd ydb
        git fetch --depth `expr $(git rev-list --count HEAD) + 1`
        # Fetch main
        git fetch origin main:main --shallow-exclude rightlib 
        git fetch --depth `expr $(git rev-list --count HEAD) + 1`
        libsha=$(git rev-parse HEAD)
        # Dev branch
        devbranch="mergelibs-${{ steps.date.outputs.dtm }}"
        git checkout main -b ${devbranch}
        prevsha=$(git rev-parse HEAD)
        git merge rightlib --no-edit
        currsha=$(git rev-parse HEAD)
        if [ ${prevsha} == ${currsha} ];then
          echo "Merge did not bring any changes, exiting"
          exit
        fi
        echo ${mainsha} > ydb/ci/rightlib.txt
        git add .
        git commit -m "Import libraries ${{ steps.date.outputs.dtm }}"
        git push --set-upstream origin mergelibs-${{ steps.date.outputs.dtm }}
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"${devbranch}","base":"main"}'
